const CategoryDetailsActionTypes = {
  FETCH_CATEGORY_DETAILS_REQUEST  : 'FETCH_CATEGORY_DETAILS_REQUEST',
  FETCH_CATEGORY_DETAILS_SUCCESS  : 'FETCH_CATEGORY_DETAILS_SUCCESS',
  FETCH_CATEGORY_DETAILS_FAILURE  : 'FETCH_CATEGORY_DETAILS_FAILURE',
}

export default CategoryDetailsActionTypes;