const UserPurchaseHistoryActionTypes = {
  FETCH_USER_PURCHASE_HISTORY_REQUEST  : 'FETCH_USER_PURCHASE_HISTORY_REQUEST',
  FETCH_USER_PURCHASE_HISTORY_SUCCESS  : 'FETCH_USER_PURCHASE_HISTORY_SUCCESS',
  FETCH_USER_PURCHASE_HISTORY_FAILURE  : 'FETCH_USER_PURCHASE_HISTORY_FAILURE',
}

export default UserPurchaseHistoryActionTypes;
