const CategoriesActionTypes = {
  FETCH_CATEGORIES_REQUEST: 'FETCH_CATEGORIES_REQUEST',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
  FETCH_CATEGORIES_GLOBAL_FAILURE: 'FETCH_CATEGORIES_GLOBAL_FAILURE',
}

export default CategoriesActionTypes;