const CategoriesTypes = {
	FETCH_CATEGORIES_REQUEST  : 'FETCH_CATEGORIES_REQUEST',
	FETCH_CATEGORIES_SUCCESS  : 'FETCH_CATEGORIES_SUCCESS',
	FETCH_CATEGORIES_FAILURE  : 'FETCH_CATEGORIES_FAILURE',
}

export default CategoriesTypes;