const GamesActionTypes = {
	FETCH_GAMES_REQUEST  : 'FETCH_GAMES_REQUEST',
	FETCH_GAMES_SUCCESS  : 'FETCH_GAMES_SUCCESS',
	FETCH_GAMES_FAILURE  : 'FETCH_GAMES_FAILURE',
}

export default GamesActionTypes;